apiVersion: v1
kind: Pod
metadata:
  name: pod-config
spec:
  containers:
    - name: nginx
      image: nginx
      envFrom: # to import all the key-value pairs from secret as environment variables
      - secretKeyRef:
          name: pod-secret