apiVersion: v1
kind: Service
metadata:
  name: nginx-LoadBalancer
spec:
  type: LoadBalancer
  selector:
    name: frontend
    project: expense
    component: frontend
    environment: dev
  ports:
    - protocol: TCP
      port: 80 # service port0
      targetPort: 80 # target port on the pod
      nodePort: 32760 # fixed node port to access the service from outside the cluster