kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-dyamic
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  # we are alreday created EFS in AWS and using that EFS file system id here.
  fileSystemId: fs-92107410
  basePath: "/expense" # optional
  